Разметка главной страницы
htmlacademy-htmlcss/1289785-technomart-31 pull request #2
Opened 2021-06-03 16:06 UTC by MariiaFish

---
:mortar_board: [Разметка главной страницы](https://up.htmlacademy.ru/htmlcss/31/user/1289785/tasks/2)

2021-06-03 16:10 UTC, MariiaFish commented on index.html
> +          <a href="+78005558628">+7 800 555-86-28</a>
Здесь хотела кнопку сделать,  но так поняла раз этот номер телефона нас куда-то приведет (свяжется с аббонентом, или тп), то здесь логичнее ссылку оставить

2021-06-03 16:16 UTC, MariiaFish commented on index.html
> +      </section>
При проверке кода в валидаторе html получила warning на все tags section без тегов h, но так как это не error, не стала править. На сколько это критично?

2021-06-03 16:22 UTC, MariiaFish commented on index.html
> +              <span>@htmlacademy.ru</span></p>
Вот здесь сомневаюсь подходит ли span

2021-06-03 16:23 UTC, MariiaFish commented on index.html
> +                <span>htmlacademy.ru</span></p>
Здесь тоже про span сомнения

2021-06-04 12:49 UTC, Dima-Dim commented on index.html
> +          <a href="+78005558628">+7 800 555-86-28</a>
Для разметки телефонов у нас есть критерий https://up.htmlacademy.ru/htmlcss/31/criteries#d29

2021-06-04 12:49 UTC, Dima-Dim commented on index.html
> +      </section>
Да, это не критично.

2021-06-04 12:50 UTC, Dima-Dim commented on index.html
> +              <span>@htmlacademy.ru</span></p>
На этапе разметки можно не использовать ни br, ни span, потому что и то и другое про стилизацию.

2021-06-04 12:50 UTC, Dima-Dim commented on index.html
> +                <span>htmlacademy.ru</span></p>
https://up.htmlacademy.ru/htmlcss/31/project/technomart#technomart-3-5

2021-06-04 13:00 UTC, Dima-Dim requested changes

2021-06-04 13:00 UTC, Dima-Dim commented on index.html
> +        <ul>
Здесь довольно разные элементы и список использовать для них не нужно.

2021-06-04 13:00 UTC, Dima-Dim commented on index.html
> +      <section>
Если заменить все div на section, то лучше не станет :) Здесь явно если и понадобится тег обёртка, то исключительно технически, а не семантически. Тоже самое с блоком выше.

2021-06-04 13:00 UTC, Dima-Dim commented on index.html
> +            <a href="#">
По макету ссылка только у текста На любой вкус.

2021-06-04 13:00 UTC, Dima-Dim commented on index.html
> +              <p>НА ВСЕ СЛУЧАИ</p>
Тексты пишем как в обычных предложениях, стилизацию будем делать позже.

2021-06-04 13:00 UTC, Dima-Dim commented on index.html
> +        <h3>Перфораторы</h3>
Обрати внимание что слайдов несколько, можно сделать это не сейчас, но нужно не забыть про это.

2021-06-04 13:00 UTC, Dima-Dim commented on index.html
> +        <figure>
Вот это всё усложнит и при этом не принесёт особой пользы в данном случае.

2021-06-04 13:00 UTC, Dima-Dim commented on index.html
> +            <a href="#">
Почему ссылка?

2021-06-04 13:00 UTC, Dima-Dim commented on index.html
> +            <img src="https://via.placeholder.com/150x100" alt="Логотип BOOSH">
https://up.htmlacademy.ru/htmlcss/31/project/technomart#technomart-3-9

2021-06-04 13:00 UTC, Dima-Dim commented on index.html
> +        <p>Мы с удовольствием доставим ваш товар прямо<br>
Тоже нужно не забыть что слайдов несколько.

2021-06-04 13:00 UTC, Dima-Dim commented on index.html
> +            <li><a href="#">Материалы</a></li>
Списка на само деле 2.

2021-06-04 13:00 UTC, Dima-Dim commented on index.html
> +            +7 800 555-86-28</p>
https://up.htmlacademy.ru/htmlcss/31/criteries#d29

2021-06-04 13:06 UTC, MariiaFish commented on index.html
> +                <span>htmlacademy.ru</span></p>
Какой стыд, я не пролистала критерии, еще думаю, как-то мало правил))

2021-06-04 13:10 UTC, Dima-Dim commented on index.html
> +                <span>htmlacademy.ru</span></p>
;)

2021-06-04 13:39 UTC, MariiaFish commented on index.html
> +        <p>Мы с удовольствием доставим ваш товар прямо<br>
Только вместо "Вперёд" и "Назад" тут  "Доставка", "Гарантия" и "Кредит&"?

2021-06-04 13:41 UTC, MariiaFish commented on index.html
> +            <img src="https://via.placeholder.com/150x100" alt="Логотип BOOSH">
Поменяла span на ссылки

2021-06-04 13:43 UTC, MariiaFish commented on index.html
> +            <a href="#">
Хороший вопрос, в требованиях не нашла такой необходимости, убираю

2021-06-04 13:44 UTC, MariiaFish commented on index.html
> +        <h3>Перфораторы</h3>
ок)

2021-06-04 13:45 UTC, MariiaFish commented on index.html
> +        <figure>
Т.е можно просто img оставить с кнопками?

2021-06-04 13:47 UTC, MariiaFish commented on index.html
> +              <p>НА ВСЕ СЛУЧАИ</p>
Я вообще просто с макета копировала, там все как-то в разнобой, оставить так, а стилями потом всё сровняется как надо?

2021-06-04 13:47 UTC, MariiaFish commented on index.html
> +            <a href="#">
Поправила

2021-06-04 13:50 UTC, MariiaFish commented on index.html
> +      <section>
Поправила

2021-06-04 13:50 UTC, MariiaFish commented on index.html
> +          <a href="+78005558628">+7 800 555-86-28</a>
поправила

2021-06-04 13:53 UTC, MariiaFish commented on index.html
> +        <ul>
Поправила

2021-06-04 13:56 UTC, MariiaFish commented on index.html
> +            <li><a href="#">Материалы</a></li>
Вот ещё же сомневалась))

2021-06-04 13:59 UTC, MariiaFish commented on index.html
> +            <li><a href="#">Материалы</a></li>
Поправила

2021-06-04 14:02 UTC, MariiaFish commented on index.html
> +            +7 800 555-86-28</p>
Поправила

2021-06-05 05:34 UTC, Dima-Dim commented on index.html
> +        <p>Мы с удовольствием доставим ваш товар прямо<br>
Ага.

2021-06-05 05:35 UTC, Dima-Dim commented on index.html
> +        <figure>
Ага.

2021-06-05 05:36 UTC, Dima-Dim commented on index.html
> +              <p>НА ВСЕ СЛУЧАИ</p>
Нет, так оставлять не надо :) надо сделать нормально и единообразно.

2021-06-08 07:52 UTC, Dima-Dim commented on index.html
> +              <p>на все случаи</p>
Тега a может быть достаточно.

2021-06-08 07:52 UTC, merged