index styles
htmlacademy-htmlcss/1289785-technomart-31 pull request #5
Opened 2021-06-24 13:48 UTC by MariiaFish

2021-06-25 06:06 UTC, Dima-Dim requested changes

2021-06-25 06:06 UTC, Dima-Dim commented on css/style.css
> +  src: url("/fonts/ptsans.woff2"),
`/fonts/ptsans.woff2` -> `../fonts/ptsans.woff2` и далее так же.

2021-06-25 06:06 UTC, Dima-Dim commented on css/style.css
> +  background: url("/img/slider/punchers-slider.png") no-repeat;
`/img/slider/punchers-slider.png` - > `../img/slider/punchers-slider.png` и далее в подобных случаях тоже.

2021-06-25 06:06 UTC, Dima-Dim commented on index.html
> +            <img class="logo" src="img/tehnomart_logo.svg" width="108" height="18" alt="Логотип иинтернет-магазина «Техномарт»">
`иинтернет-магазина` -> `интернет-магазина` :)

2021-06-25 09:03 UTC, MariiaFish commented on index.html
> +            <div class="order-rectangle">
ты имеешь в виду div с классом  "order-rectangle"? Или я  не так понимаю слово контейнер

2021-06-25 09:07 UTC, MariiaFish commented on css/style.css
> +  src: url("/fonts/ptsans.woff2"),
в одну строчку можно сделать, да?

2021-06-25 09:10 UTC, MariiaFish commented on css/style.css
> +  background: url("/img/slider/punchers-slider.png") no-repeat;
Поправила, но отличия не понимаю, можешь рассказать про это?

2021-06-25 09:11 UTC, MariiaFish commented on css/style.css
> +  src: url("/fonts/ptsans.woff2"),
поправила

2021-06-25 09:12 UTC, MariiaFish commented on index.html
> +            <img class="logo" src="img/tehnomart_logo.svg" width="108" height="18" alt="Логотип иинтернет-магазина «Техномарт»">
поправила)

2021-06-28 04:19 UTC, Dima-Dim commented on index.html
> +            <div class="order-rectangle">
Да div это один из контейнеров и кажется он тут лишний.

2021-06-28 04:21 UTC, Dima-Dim commented on css/style.css
> +  background: url("/img/slider/punchers-slider.png") no-repeat;
Да, у Вас должен быть материал про абсолютные и относительные пути к файлам. В твоём варианте при публикации проекта на GitHub сервер не находит изображений потому что путь получается не верный.

2021-06-28 10:22 UTC, MariiaFish commented on index.html
> +            <div class="order-rectangle">
поправила

2021-07-01 08:35 UTC, Dima-Dim commented on css/style.css
> +  height: 45px;
Может вызвать проблемы при переполнении.

2021-07-01 08:35 UTC, Dima-Dim commented on css/style.css
> +  height: 38px;
Тоже опасная высота.

2021-07-01 08:35 UTC, Dima-Dim commented on css/style.css
> +  height: 61px;
В общем везде где есть текст и ограничена высота - опасно.

2021-07-01 08:35 UTC, Dima-Dim commented on css/style.css
> +/* Не работаеь этот селектор, его перечеркивает user agent stylesheet h2 */
Не может такого быть :) user agent селекторы имеют наименьший приоритет.

2021-07-01 08:35 UTC, merged